#!/usr/bin/env python

"""\
Tinybat - a standalone battery monitor for the rest of us.

@author: Aaron Mavrinac
@contact: mavrinac@gmail.com
@license: GPL-3
"""

import os
import gtk
from gobject import timeout_add
from sys import prefix


sharepath = os.path.join( prefix, "share/tinybat" )
if not os.path.isdir( sharepath ):
    sharepath = "../data"


class BatteryStatusIcon( gtk.StatusIcon ):
    """\
    Battery monitor status icon class, derived from GTK StatusIcon.
    """
    def __init__( self ):
        """\
        Constructor.
        """
        gtk.StatusIcon.__init__( self )
        self.file_adpst = "/sys/class/power_supply/ADP0/online"
        self.file_batst = "/sys/class/power_supply/BAT0/status"
        self.file_batcf = "/sys/class/power_supply/BAT0/charge_full"
        self.file_batcn = "/sys/class/power_supply/BAT0/charge_now"
        self.set_from_file( os.path.join( sharepath, "icons",
                            "battery-missing.png" ) )
        self.set_visible( True )
        self.update()
        # update every 5 seconds
        timeout_add( 5000, self.on_timeout )

    def update( self ):
        """\
        Update the status icon.
        """
        # set icon
        icon = "battery-"
        if self.battery_level == 100.0 and self.ac_adapter_online:
            icon += "charged"
        elif self.battery_level > 95.0:
            icon += "100"
        else:
            icon += "%03d" % ( int( self.battery_level ) \
                - int( self.battery_level ) % 20 )
        if self.battery_level < 100.0 and self.battery_charging:
            icon += "-charging"
        self.set_from_file( os.path.join( sharepath, "icons", icon + ".png" ) )
        # set tooltip
        tooltip = "Battery " + str( int( self.battery_level ) ) + "% (" + \
                  open( self.file_batst ).readline().rstrip() + ")"
        self.set_tooltip( tooltip )

    def on_timeout( self ):
        """\
        Timeout callback for update.
        """
        self.update()
        return True

    @property
    def ac_adapter_online( self ):
        """\
        Returns whether the AC adapter is on-line.
        """
        if open( self.file_adpst ).readline().rstrip() == '1':
            return True
        return False

    @property
    def battery_charging( self ):
        """\
        Returns whether the battery is charging.
        """
        if open( self.file_batst ).readline().rstrip() == 'Charging':
            return True
        return False

    @property
    def battery_level( self ):
        """\
        Returns the battery level as a percentage.
        """
        return 100.0 * \
            float( open( self.file_batcn ).readline() ) \
            / float( open( self.file_batcf ).readline() )


if __name__ == '__main__':
    tb = BatteryStatusIcon()
    gtk.main()
